project:
  type: website

website:
  title: "Data and Tech Handbook (archived)"
  description: "This site has moved to https://data.poverty-action.org"

format:
  html:
    theme: cosmo
    toc: false
