project:
  type: website
  preview:
    port: 3434
    browser: true
execute:
  freeze: auto
website:
  title: "Data and Tech Handbook"
  announcement:
    dismissable: false
    content: "**Welcome!** - This site is an early draft and prototype. Content, pages, and the site are subject to change."
    position: above-navbar
    type: warning
    icon: cone-striped
  description:  "Handbook for common, shared practices for data science and engineering at Innovations for Poverty Action."
  favicon: ./assets/images/IPA-primary-full-color-abbreviated.png
  # site-url: https://research.poverty-action.org
  repo-url: https://github.com/PovertyAction/ipa-data-tech-handbook
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  reader-mode: false
  search:
    show-item-context: true
    location: sidebar
    type: textbox
    limit: 20
  page-footer:
    left: |
      Brought to you by
      [![](../../assets/images/IPA-primary-color-RGB.png){fig-alt="IPA" width=65px}](https://poverty-action.org)
    # center:
    #   - text: "About"
    #     href: about.qmd
    #   - text: "FAQ"
    #     href: docs/faq/index.qmd
    #   - text: "License"
    #     href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/poverty_action
        aria-label: IPA Twitter
      - icon: github
        href: https://github.com/PovertyAction/ipa-data-tech-handbook
        aria-label: IPA GitHub
      # - icon: rss
        # href: https://povertyaction.github.io/ipa-data-tech-handbook/docs/blog/index.xml
        # aria-label: IPA Blog RSS
  sidebar:
    background: '#155240'
    foreground: '#ffffff'
    logo: ./assets/images/IPA-primary-white-abbreviated.png
    collapse-level: 1
    search: true
    style: "docked"
    contents:
      - href: index.qmd
        text: Home

      - section: Guides
        contents:
        - href: ./guides/computer_setup.qmd
          text: Computer Setup
        - href: ./guides/venv.qmd
          text: Virtual Environments
        - href: ./guides/code_review.qmd
          text: Code Review
        - href: ./guides/pre_commit_hooks.qmd
          text: pre-commit

      - section: Software
        contents:
          - href: ./software/git.qmd
            text: Git
          - href: ./software/github.qmd
            text: GitHub
          - href: ./software/vscode.qmd
            text: VS Code
          - href: ./software/quarto.qmd
            text: Quarto
          - href: ./software/python.qmd
            text: Python
          - href: ./software/stata.qmd
            text: Stata
          - href: ./software/sql.qmd
            text: SQL

      - section: Methods
        contents:
          - href: ./methods/references.qmd
            text: References

      - section: Teams
        contents:
          - href: ./teams/dse.qmd
            text: DSE
          - href: ./teams/grds.qmd
            text: GRDS
          - href: ./teams/mist.qmd
            text: MIST
          - href: ./teams/ppi.qmd
            text: PPI

      - href: ./contributing.qmd
        text: Contributing

# bibliography: ./assets/references.bib

format:
  html:
    output-ext: html
    template-partials:
      - ./assets/title-block.html
      - ./assets/toc.html
    title-block-banner: false
    theme:
      light: [cosmo, ./assets/theme.scss]
    toc: true
    code-background: true
    code-copy: true
    code-overflow: wrap
    css: ./assets/styles.css
    include-after-body: ./assets/js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
