project:
  type: website

website:
  title: "Data and Tech Handbook"
  description:  "Handbook for common, shared practices for data science and engineering at Innovations for Poverty Action."
  favicon: ./handbook/images/IPA-primary-full-color-abbreviated.png
  repo-url: https://github.com/PovertyAction/dse_handbook
  repo-actions: [edit, issue]
  bread-crumbs: false
  reader-mode: true
  search:
    location: navbar
    type: overlay
  navbar:
    background: '#155240'
    foreground: '#ffffff'
    logo: ./handbook/images/IPA-primary-white-abbreviated.png
    collapse: true
    right:
      - href: ./handbook/index.qmd
        text: Home
      - href: ./handbook/computer_setup.qmd
        text: Setup

format:
  html:
    # for sharepoint: use aspx
    # reference: https://github.com/quarto-dev/quarto-cli/discussions/3535#discussioncomment-9111419
    output-ext: html
    css: ./handbook/assets/style_ipa.css
    toc: true
