project:
  type: website
  preview:
    port: 3434
    browser: true
execute:
  freeze: auto
website:
  title: "Data and Tech Handbook"
  announcement:
    dismissable: false
    content: "**Welcome!** - This handbook is an early draft and prototype. Content, pages, and the site are subject to change."
    position: below-navbar
    type: warning
    icon: cone-striped
  description:  "Handbook for common, shared practices for data science and engineering at Innovations for Poverty Action."
  favicon: ./docs/assets/images/IPA-primary-full-color-abbreviated.png
  # site-url: https://research.poverty-action.org
  repo-url: https://github.com/PovertyAction/ipa-data-tech-handbook
  repo-actions: [edit, issue]
  bread-crumbs: true
  reader-mode: false
  search:
    location: navbar
    type: overlay
    limit: 20
  page-footer:
    left: |
      Brought to you by
      [![](../../docs/assets/images/IPA-primary-color-RGB.png){fig-alt="IPA" width=65px}](https://poverty-action.org)
    # center:
    #   - text: "About"
    #     href: about.qmd
    #   - text: "FAQ"
    #     href: docs/faq/index.qmd
    #   - text: "License"
    #     href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/poverty_action
        aria-label: IPA Twitter
      - icon: github
        href: https://github.com/PovertyAction/ipa-data-tech-handbook
        aria-label: IPA GitHub
      # - icon: rss
        # href: https://povertyaction.github.io/ipa-data-tech-handbook/docs/blog/index.xml
        # aria-label: IPA Blog RSS
  sidebar:
    background: '#155240'
    foreground: '#ffffff'
    logo: ./docs/assets/images/IPA-primary-white-abbreviated.png
    collapse-level: 1
    search: true
    style: "floating"
    contents:
      - href: ./docs/index.md
        text: Home

      - section: About
        contents:
        - href: ./docs/about/foundations.md
          text: Foundations
        - href: ./docs/about/mmds.md
          text: Minimum Must Dos
        - href: ./docs/about/ipa_researchers.md
          text: For IPA Researchers
        - href: ./docs/about/ipa_staff.md
          text: For IPA staff

      - section: Software Guides
        contents:
          - href: ./docs/software/coding_best_practices.md
            text: Coding Best Practices
          - href: ./docs/software/surveycto.md
            section: SurveyCTO
            contents: 
              - href: ./docs/software/surveycto/scto_best_practices.md
                text: "SurveyCTO: Best Practices"
              - href: ./docs/software/surveycto/scto_ipa_tools.md
                text: "SurveyCTO: IPA Tools"

          - href: ./docs/software/Stata.md
            text: Stata
          - href: ./docs/software/ml.md
            text: Machine Learning

#    right:
      # - text: Blog
      #   href: ./docs/blog/index.qmd
#     - text: Contributing
#      href: ./docs/contributing.md

    # tools:
    #   - icon: github
    #     href: https://github.com/povertyaction
    #     aria-label: IPA GitHub
    #   - icon: twitter
    #     href: https://twitter.com/poverty_action
    #     aria-label: IPA Twitter
      # - icon: rss
        # href: https://povertyaction.github.io/ipa-data-tech-handbook/docs/blog/index.xml
        # aria-label: IPA Blog RSS

format:
  html:
    # for sharepoint: use aspx
    # reference: https://github.com/quarto-dev/quarto-cli/discussions/3535#discussioncomment-9111419
    output-ext: html
    template-partials:
      - ./docs/assets/title-block.html
      - ./docs/assets/toc.html
    title-block-banner: false
    # css: ./docs/assets/style_ipa.css
    theme: cosmo
    toc: true
    code-background: true
    code-copy: true
