---
title: IPA Data Science, Engineering, and Technology Handbook
---

## About the Handbook

Welcome to IPA's Handbook for Data Science, Engineering, and Technology!

This handbook is intended as a living document to assist IPA staff and collaborators
with common practices for writing code and working with data. The handbook will never be
comprehensive of every possible software, data object, or shared practice. However, IPA
staff working with data and technology are encouraged to use this handbook as a
reference and a shared project to give tips and advice for working collaboratively with
data analysis and software development.

### Getting Started

To get started with software covered in this handbook, read
[Computer Setup](./guides/computer_setup.qmd) to learn how to set up your computer for
data analysis and software development.

### Contributing

For instructions on how to contribute to this handbook, see
[Contributing](contributing.qmd) to the Handbook.

Also, see the [Code Review](./guides/code_review.qmd) guide for information on how to
conduct code reviews.

### Using Software Tools

For information about specific software, see the respective pages under the `Software`
directory.

Here are some specific software that this guide covers:

- [Git](./software/git.qmd)
- [Github](./software/github.qmd)
- [VS Code](./software/vscode.qmd)
- [Quarto](./software/quarto.qmd)
- [Python](./software/python.qmd)
- and more!

### Acknowledgements

This handbook is a collaboration between multiple IPA Teams including
[Data Science and Engineering (DSE)](./teams/dse.qmd),
[Management and Information Systems Team (MIST)](./teams/mist.qmd),
[Global Research and Data Support](./teams/grds.qmd), and
[Poverty Probability Index (PPI®)](./teams/ppi.qmd).

The handbook is inspired by the
[Gitlab Data Team Handbook](https://handbook.gitlab.com/handbook/business-technology/data-team/).
