---
title: Stata
execute:
    eval: true
# Editors are the "Maintainers" of the page
# editors:
#  - "[Niall Keleher](https://poverty-action.org/people/niall-keleher)"

# Authors are the "Contributors" of the page
# Add your name to the list if you have contributed to this page
# author:
#   - Niall Keleher
---

## What is Stata?

Stata is a statistical software package that is commonly used in the social sciences and economics.
It is widely used at IPA for data analysis and management. It offers a comprehensive
library of methods for data cleaning, descriptive statistics, and econometric analysis.
Stata is very well suited for research data workflows and research design tasks,
including power calculations, sample design adjustments, panel data analysis,
time series analysis, etc. See [Stata Features](https://www.stata.com/features/)
for a full list of what Stata makes available.

## How to install Stata?

IPA staff can download and install the relevant version (`.exe` for Windows,
`.dmg` for MacOS, or  `.tar.gz` for Linux) from IPA on the Box
[installation packages](https://ipastorage.app.box.com/folder/129276324764?v=install-stata).

## Coding Conventions

See the following resources for coding conventions in Stata:

- [DIME Analytics Stata Style Guide](https://worldbank.github.io/dime-data-handbook/coding.html#the-dime-analytics-stata-style-guide)
- [Sean Higgins's Stata guide](https://github.com/skhiggins/Stata_guide)
on GitHub.
- [Coding and Data for the Social Sciences](https://web.stanford.edu/~gentzkow/research/CodeAndData.xhtml#magicparlabel-1248),
by Matthew Gentzkow and Jesse Shapiro

## Using Stata from Python

Within a Python script or Jupyter Notebook, you can call Stata using [pystata](https://www.stata.com/python/pystata18/notebook/Quick%20Start0.html).

```{python}
import stata_setup

# set configuration to the path where Stata is installed and the flavor of Stata
# in the case below, we're using Stata 18 SE
stata_setup.config("C:/Program Files/Stata18/", "se")
```


### Call Stata using pystata API functions

```{python}
from pystata import stata
```

```{python}
stata.run(
    """
    sysuse auto, clear
    reg mpg price i.foreign
    """
)
```


Or use IPython magic commands to run Stata code in a Jupyter Notebook.

```{python}
%%stata
sysuse auto, clear
describe
```


```{python}
%stata scatter mpg price
```


## Data Visualization

Consider installing the [ipaplots](https://github.com/PovertyAction/ipaplots) for the IPA graph schema in Stata.

## Learning References

For more information on learning and using Stata, see the
[IPA-Stata-Trainings](https://github.com/PovertyAction/IPA-Stata-Trainings) repository on GitHub.

- [Stata Video Tutorials](https://www.stata.com/links/video-tutorials/)
